### ISSUE TITLE
why would we create a new IdeasRepo in the hook?

### ISSUE THREAD

**Issue by duongphuhiep** [jmagrippis/techy-cat#8]
AFAIK the codes in the hook will be executed for EVERY requests to the server, so it will create a new IdeasRepo for every un-related requests. 

I think it is not quite right to [create a new IdeasRepo in the hook](https://github.com/jmagrippis/techy-cat/blob/main/src/hooks/index.ts#L28).

I assume that you are doing it to hide the IdeasRepo creation (with suparbase login/password) on the server side codes.
But is it the only way? Is it possible to create a new IdeasRepo on-demand where we really need it (in the handler)? or having server-side codes in the handler?

**Comment by jmagrippis** [comment]
Hey @duongphuhiep , thanks for raising this! We’re trying to explore the best ways to do things, so discussions always welcome 😄 And of course, there’s a variety of ways to do this, I did try a few before going with this implementation, as I was recording for the Endpoints video!

My thinking here is:

- We defo want to create the Supabase client in a hook (whether inside the ‘handle’ method, or as part of a sequence), because we want to authorise it according to the user (and get starred ideas thanks to Row Level Security, do our CRUD in the dashboard areas with RLS etc.)
- *However*, we could put the Supabase client in the ‘locals’ instead, and then anything that needs it, gets it from the ‘locals’ and passes it to create their instance of ‘ideasRepo’ or whatever. I think that’d be fine, but…
- I think it’s more convenient for every handler / load method to have access to all the repos “just in case” they need them. Creating these instances doesn’t actually open an extra connection or anything. I don’t think you can measure the performance implication of creating those instances even on a benchmark, it’d be minuscule! So I’m not concerned with having it available even for handlers that don’t need it.

And that’s pretty much it! In other words, I do want to create the Supbase client in the hook for auth reasons, but figured it’d be handier to put the repos in the locals instead of the client itself.

—

Having used it like this for a bit, I’m not thrilled with the “Typescript support”, the type definitions / IDE help! I think storing the client in the locals and creating the instances as needed would make my life easier command+clicking methods (instead of getting to the interface definitions). So, I’m not concerned with the performance implications, I don’t think UX-wise it’d make a difference, but maybe DevEx would be better 🙂

Also, I say “I defo want to create the Supabase client for every request”, but maybe you think differently 😄 so I’ll be happy to hear your thoughts again, having read this!

**Comment by duongphuhiep** [comment]
Thank you for your response, the choice you make are for good reason, and performance / memory is not my direct concern.

From a backend developer's perspective, I'm trying to look for aspects which often are over looked by frontend developers:

1) the objects lifetime on server side.
2) the objects access scope on server side.

---

1) The object life time could be
  * **singleton**: the object is created once and live until the server gone down
  * **scoped**: the object is created for each request to server and destroyed when server complete the request
  * **transient**: the object is created whenever it is needed and get destroyed just after it is used.

The object life time decides where/when/how we should create the object.

In our example:

All our objects (supabaseClient, userRepo, ideasRepo) are "scoped": they are created when the request arrive, and die (garbage-collected) when the request is completed. So, things to consider:
 * should SupabaseClient be a scoped object (as we did) or a Singleton is enough? which means that we might create the SupabaseClient and all the repository once when the server is started? what is the recommendation from Supabase for the client lifetime? should it be a long live object?
 * How to create and access a Singleton on the server side?

2) the objects access scope:

All the repository are accessible from anywhere through `event.locals` so they are not much different from global variables.
it is convenient to work with global variables but, not a good idea when application scale up to complexity.
Other server-side languages (C#, java..) often give just enough access so that from inside a function, we usually don't have access to unrelated objects. How could we achieve the same thing?

**Comment by duongphuhiep** [comment]
I was just typing things which wrapped around my head, so please you don't waste your time to read all of these... Now when I think about it, all these concerns are not worth consider if our application stay relatively simple: 
* no complex business logic, 
* no complex dependency graph between objects. 

My conclusion is that

our Svelte app should only focus on the UX, and stay.. beautiful! When it come to heavy business logics, they should be delegated to other micro-service (java, C#, golang..).. all problem is solved :+1:
